-- MySQL Script generated by MySQL Workbench
-- Wed Jul 25 06:23:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teamf-2018summer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teamf-2018summer
-- -----------------------------------------------------
USE `teamf-2018summer` ;

-- -----------------------------------------------------
-- Table `teamf-2018summer`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamf-2018summer`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `teamf-2018summer`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamf-2018summer`.`user` (
  `fname` VARCHAR(20) NOT NULL,
  `lname` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `email_verify` TINYINT NULL,
  `token` VARCHAR(45) NULL,
  `hash_passwd` VARCHAR(60) NULL,
  `usn` INT NOT NULL,
  PRIMARY KEY (`usn`),
  UNIQUE INDEX `usn_UNIQUE` (`usn` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamf-2018summer`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamf-2018summer`.`location` (
  `longitude` FLOAT NOT NULL,
  `latitude` FLOAT NOT NULL,
  `location_num` INT NOT NULL,
  PRIMARY KEY (`location_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamf-2018summer`.`air_sensor_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamf-2018summer`.`air_sensor_list` (
  `air_sensor_id` VARCHAR(45) NOT NULL,
  `usn` INT NOT NULL,
  `location_num` INT NOT NULL,
  PRIMARY KEY (`air_sensor_id`, `usn`, `location_num`),
  INDEX `fk_user_sensor_user1_idx` (`usn` ASC),
  INDEX `fk_air_sensor_list_location1_idx` (`location_num` ASC),
  CONSTRAINT `fk_user_sensor_user1`
    FOREIGN KEY (`usn`)
    REFERENCES `teamf-2018summer`.`user` (`usn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_air_sensor_list_location1`
    FOREIGN KEY (`location_num`)
    REFERENCES `teamf-2018summer`.`location` (`location_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamf-2018summer`.`air_sensor_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamf-2018summer`.`air_sensor_data` (
  `co` FLOAT NULL,
  `co2` FLOAT NULL,
  `so2` FLOAT NULL,
  `no2` FLOAT NULL,
  `temperature` FLOAT NULL,
  `collected_time` TIMESTAMP NOT NULL,
  `pm2.5` FLOAT NULL,
  `pm10` FLOAT NULL,
  `air_sensor_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`collected_time`, `air_sensor_id`),
  INDEX `fk_air_sensor_data_air_sensor_list1_idx` (`air_sensor_id` ASC),
  CONSTRAINT `fk_air_sensor_data_air_sensor_list1`
    FOREIGN KEY (`air_sensor_id`)
    REFERENCES `teamf-2018summer`.`air_sensor_list` (`air_sensor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamf-2018summer`.`polar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamf-2018summer`.`polar` (
  `polar_sensor_id` VARCHAR(20) NOT NULL,
  `usn` INT NOT NULL,
  PRIMARY KEY (`polar_sensor_id`, `usn`),
  INDEX `fk_polar_user1_idx` (`usn` ASC),
  CONSTRAINT `fk_polar_user1`
    FOREIGN KEY (`usn`)
    REFERENCES `teamf-2018summer`.`user` (`usn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamf-2018summer`.`polar_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamf-2018summer`.`polar_data` (
  `heartrate` INT NOT NULL,
  `rr_interval` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `polar_sensor_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`polar_sensor_id`),
  CONSTRAINT `fk_polar_data_polar1`
    FOREIGN KEY (`polar_sensor_id`)
    REFERENCES `teamf-2018summer`.`polar` (`polar_sensor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
